wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1632080887
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.9.6
      5: 0.12.1
      8:
      - 5
alpha:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 1
dataset:
  desc: null
  value: modelnet
full_dataset:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.001
logger:
  desc: null
  value: true
model_path:
  desc: null
  value: final_model.pt
num_epochs:
  desc: null
  value: 10
retrain_path:
  desc: null
  value: null
